nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        # allow_origin: ['*']
        allow_methods: ['GET', 'POST', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    # paths:
    #     '^/api':
    #         # only mobile app
    #         allow_origin: ['*']
    #         # allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
    #         # allow_headers: ['*']
    #         # headers need Bearer token
    #         allow_headers: ['Content-Type', 'Authorization']
    #         allow_methods: ['GET', 'POST', 'PATCH', 'DELETE']
    #         max_age: 3600