nelmio_security:
    # signs/verifies all cookies
    #signed_cookie:
    # autorize f2a bundle and sf redirect
        #names: ['*']

    # prevents framing of the entire site
    clickjacking:
        paths:
            '^/.*': DENY

    # disables content type sniffing for script resources
    content_type:
        nosniff: true

    # forces Microsoft's XSS-Protection with
    # its block mode
    xss_protection:
        enabled: true
        mode_block: true

    # Send a full URL in the `Referer` header when performing a same-origin request,
    # only send the origin of the document to secure destination (HTTPS->HTTPS),
    # and send no header to a less secure destination (HTTPS->HTTP).
    # If `strict-origin-when-cross-origin` is not supported, use `no-referrer` policy,
    # no referrer information is sent along with requests.
    referrer_policy:
        enabled: true
        policies:
            - 'no-referrer'
            - 'strict-origin-when-cross-origin'
    csp:
        enabled: false
        enforce:
            # see full description below
            level1_fallback: true
            # only send directives supported by the browser, defaults to false
            # this is a port of https://github.com/twitter/secureheaders/blob/83a564a235c8be1a8a3901373dbc769da32f6ed7/lib/secure_headers/headers/policy_management.rb#L97
            browser_adaptive:
                enabled: false
            
            report-uri: '%router.request_context.base_url%/nelmio/csp/report'
            
            default-src: [ 'self']
            
            # allow mercure.simschab.cloud
            connect-src: [ 'self', 'https://mercure.simschab.cloud' ]
            # frame-src: [ 'https://www.youtube.com' ]
            
            script-src:
                - 'self'
                - 'unsafe-inline'
                - 'https://127.0.0.1:8000/bundles/easyadmin/app.js'
                - 'https://obaby.simschab.cloud/bundles/easyadmin/app.js'
                
            img-src:
                - 'https://randomuser.me'
                - 'https://127.0.0.1:8000/favicon.ico'
                - 'https://obaby.simschab.cloud/favicon.ico'
                - 'data:' 
            
            style-src:
                - 'self'
                - 'unsafe-inline'
                - 'https://fonts.googleapis.com'

            font-src:
                - 'self'
                - 'https://fonts.gstatic.com'

            block-all-mixed-content: true # defaults to false, blocks HTTP content over HTTPS transport
            upgrade-insecure-requests: true # defaults to false, upgrades HTTP requests to HTTPS transport
        
        report:
            level1_fallback: true
            # only send directives supported by the browser, defaults to false
            # this is a port of https://github.com/twitter/secureheaders/blob/83a564a235c8be1a8a3901373dbc769da32f6ed7/lib/secure_headers/headers/policy_management.rb#L97
            browser_adaptive:
                enabled: true
            report-uri: '%router.request_context.base_url%/nelmio/csp/report'

        
        